export type NameOfAllah = {
  n: number;
  ar: string;
  en: string;
  meaning: string;
};

export const ASMAUL_HUSNA: NameOfAllah[] = [
  { n: 1, ar: "الرحمن", en: "Ar-Rahman", meaning: "The Most Gracious" },
  { n: 2, ar: "الرحيم", en: "Ar-Rahim", meaning: "The Most Merciful" },
  { n: 3, ar: "الملك", en: "Al-Malik", meaning: "The King, The Sovereign" },
  { n: 4, ar: "القدوس", en: "Al-Quddus", meaning: "The Most Holy" },
  { n: 5, ar: "السلام", en: "As-Salam", meaning: "The Source of Peace" },
  { n: 6, ar: "المؤمن", en: "Al-Mu'min", meaning: "The Guardian of Faith" },
  { n: 7, ar: "المهيمن", en: "Al-Muhaymin", meaning: "The Protector" },
  { n: 8, ar: "العزيز", en: "Al-Aziz", meaning: "The Almighty" },
  { n: 9, ar: "الجبار", en: "Al-Jabbar", meaning: "The Compeller" },
  { n: 10, ar: "المتكبر", en: "Al-Mutakabbir", meaning: "The Majestic" },
  { n: 11, ar: "الخالق", en: "Al-Khaliq", meaning: "The Creator" },
  { n: 12, ar: "البارئ", en: "Al-Bari'", meaning: "The Evolver" },
  { n: 13, ar: "المصور", en: "Al-Musawwir", meaning: "The Fashioner" },
  { n: 14, ar: "الغفار", en: "Al-Ghaffar", meaning: "The Ever-Forgiving" },
  { n: 15, ar: "القهار", en: "Al-Qahhar", meaning: "The Subduer" },
  { n: 16, ar: "الوهاب", en: "Al-Wahhab", meaning: "The Bestower" },
  { n: 17, ar: "الرزاق", en: "Ar-Razzaq", meaning: "The Provider" },
  { n: 18, ar: "الفتاح", en: "Al-Fattah", meaning: "The Opener" },
  { n: 19, ar: "العليم", en: "Al-Alim", meaning: "The All-Knowing" },
  { n: 20, ar: "القابض", en: "Al-Qabid", meaning: "The Constrictor" },
  { n: 21, ar: "الباسط", en: "Al-Basit", meaning: "The Expander" },
  { n: 22, ar: "الخافض", en: "Al-Khafid", meaning: "The Abaser" },
  { n: 23, ar: "الرافع", en: "Ar-Rafi", meaning: "The Exalter" },
  { n: 24, ar: "المعز", en: "Al-Mu'izz", meaning: "The Bestower of Honour" },
  { n: 25, ar: "المذل", en: "Al-Mudhill", meaning: "The Humiliator" },
  { n: 26, ar: "السميع", en: "As-Sami", meaning: "The All-Hearing" },
  { n: 27, ar: "البصير", en: "Al-Basir", meaning: "The All-Seeing" },
  { n: 28, ar: "الحكم", en: "Al-Hakam", meaning: "The Judge" },
  { n: 29, ar: "العدل", en: "Al-Adl", meaning: "The Just" },
  { n: 30, ar: "اللطيف", en: "Al-Latif", meaning: "The Subtle" },
  { n: 31, ar: "الخبير", en: "Al-Khabir", meaning: "The All-Aware" },
  { n: 32, ar: "الحليم", en: "Al-Halim", meaning: "The Forbearing" },
  { n: 33, ar: "العظيم", en: "Al-Azim", meaning: "The Magnificent" },
  { n: 34, ar: "الغفور", en: "Al-Ghafur", meaning: "The Forgiving" },
  { n: 35, ar: "الشكور", en: "Ash-Shakur", meaning: "The Appreciative" },
  { n: 36, ar: "العلي", en: "Al-Ali", meaning: "The Most High" },
  { n: 37, ar: "الكبير", en: "Al-Kabir", meaning: "The Greatest" },
  { n: 38, ar: "الحفيظ", en: "Al-Hafiz", meaning: "The Preserver" },
  { n: 39, ar: "المقيت", en: "Al-Muqit", meaning: "The Nourisher" },
  { n: 40, ar: "الحسيب", en: "Al-Hasib", meaning: "The Reckoner" },
  { n: 41, ar: "الجليل", en: "Al-Jalil", meaning: "The Sublime" },
  { n: 42, ar: "الكريم", en: "Al-Karim", meaning: "The Generous" },
  { n: 43, ar: "الرقيب", en: "Ar-Raqib", meaning: "The Watcher" },
  { n: 44, ar: "المجيب", en: "Al-Mujib", meaning: "The Responsive" },
  { n: 45, ar: "الواسع", en: "Al-Wasi", meaning: "The Vast" },
  { n: 46, ar: "الحكيم", en: "Al-Hakim", meaning: "The Wise" },
  { n: 47, ar: "الودود", en: "Al-Wadud", meaning: "The Loving" },
  { n: 48, ar: "المجيد", en: "Al-Majid", meaning: "The Glorious" },
  { n: 49, ar: "الباعث", en: "Al-Ba'ith", meaning: "The Resurrector" },
  { n: 50, ar: "الشهيد", en: "Ash-Shahid", meaning: "The Witness" },
  { n: 51, ar: "الحق", en: "Al-Haqq", meaning: "The Truth" },
  { n: 52, ar: "الوكيل", en: "Al-Wakil", meaning: "The Trustee" },
  { n: 53, ar: "القوي", en: "Al-Qawiyy", meaning: "The Strong" },
  { n: 54, ar: "المتين", en: "Al-Matin", meaning: "The Firm" },
  { n: 55, ar: "الولي", en: "Al-Waliyy", meaning: "The Protecting Friend" },
  { n: 56, ar: "الحميد", en: "Al-Hamid", meaning: "The Praiseworthy" },
  { n: 57, ar: "المحصي", en: "Al-Muhsi", meaning: "The Counter" },
  { n: 58, ar: "المبدئ", en: "Al-Mubdi'", meaning: "The Originator" },
  { n: 59, ar: "المعيد", en: "Al-Mu'id", meaning: "The Restorer" },
  { n: 60, ar: "المحيي", en: "Al-Muhyi", meaning: "The Giver of Life" },
  { n: 61, ar: "المميت", en: "Al-Mumit", meaning: "The Bringer of Death" },
  { n: 62, ar: "الحي", en: "Al-Hayy", meaning: "The Ever-Living" },
  { n: 63, ar: "القيوم", en: "Al-Qayyum", meaning: "The Self-Existing" },
  { n: 64, ar: "الواجد", en: "Al-Wajid", meaning: "The Finder" },
  { n: 65, ar: "الماجد", en: "Al-Majid", meaning: "The Noble" },
  { n: 66, ar: "الواحد", en: "Al-Wahid", meaning: "The One" },
  { n: 67, ar: "الأحد", en: "Al-Ahad", meaning: "The Unique" },
  { n: 68, ar: "الصمد", en: "As-Samad", meaning: "The Eternal" },
  { n: 69, ar: "القادر", en: "Al-Qadir", meaning: "The Able" },
  { n: 70, ar: "المقتدر", en: "Al-Muqtadir", meaning: "The Powerful" },
  { n: 71, ar: "المقدم", en: "Al-Muqaddim", meaning: "The Expediter" },
  { n: 72, ar: "المؤخر", en: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { n: 73, ar: "الأول", en: "Al-Awwal", meaning: "The First" },
  { n: 74, ar: "الآخر", en: "Al-Akhir", meaning: "The Last" },
  { n: 75, ar: "الظاهر", en: "Az-Zahir", meaning: "The Manifest" },
  { n: 76, ar: "الباطن", en: "Al-Batin", meaning: "The Hidden" },
  { n: 77, ar: "الوالي", en: "Al-Wali", meaning: "The Governor" },
  { n: 78, ar: "المتعالي", en: "Al-Muta'ali", meaning: "The Most Exalted" },
  { n: 79, ar: "البر", en: "Al-Barr", meaning: "The Source of Goodness" },
  { n: 80, ar: "التواب", en: "At-Tawwab", meaning: "The Ever-Pardoning" },
  { n: 81, ar: "المنتقم", en: "Al-Muntaqim", meaning: "The Avenger" },
  { n: 82, ar: "العفو", en: "Al-Afuw", meaning: "The Pardoner" },
  { n: 83, ar: "الرؤوف", en: "Ar-Ra'uf", meaning: "The Kind" },
  { n: 84, ar: "مالك الملك", en: "Malik-ul-Mulk", meaning: "The Owner of Sovereignty" },
  { n: 85, ar: "ذو الجلال والإكرام", en: "Dhu-al-Jalal wa-al-Ikram", meaning: "The Lord of Majesty & Bounty" },
  { n: 86, ar: "المقسط", en: "Al-Muqsit", meaning: "The Equitable" },
  { n: 87, ar: "الجامع", en: "Al-Jami'", meaning: "The Gatherer" },
  { n: 88, ar: "الغني", en: "Al-Ghani", meaning: "The Self-Sufficient" },
  { n: 89, ar: "المغني", en: "Al-Mughni", meaning: "The Enricher" },
  { n: 90, ar: "المانع", en: "Al-Mani'", meaning: "The Preventer" },
  { n: 91, ar: "الضار", en: "Ad-Darr", meaning: "The Distresser" },
  { n: 92, ar: "النافع", en: "An-Nafi'", meaning: "The Bestower of Benefits" },
  { n: 93, ar: "النور", en: "An-Nur", meaning: "The Light" },
  { n: 94, ar: "الهادي", en: "Al-Hadi", meaning: "The Guide" },
  { n: 95, ar: "البديع", en: "Al-Badi'", meaning: "The Incomparable" },
  { n: 96, ar: "الباقي", en: "Al-Baqi", meaning: "The Everlasting" },
  { n: 97, ar: "الوارث", en: "Al-Warith", meaning: "The Inheritor" },
  { n: 98, ar: "الرشيد", en: "Ar-Rashid", meaning: "The Guide to Right Path" },
  { n: 99, ar: "الصبور", en: "As-Sabur", meaning: "The Patient" },
];
